/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            authId?: string;
            /** @default false */
            isAdmin: boolean | null;
            account?: components["schemas"]["Account"] | null;
            admin?: components["schemas"]["Admin"] | null;
        };
        Admin: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            email?: string | null;
            user?: components["schemas"]["User"];
            userId?: string;
            createdCategories?: components["schemas"]["Category"][];
            lastModifiedCategories?: components["schemas"]["Category"][];
            createdTags?: components["schemas"]["Tag"][];
            lastModifiedTags?: components["schemas"]["Tag"][];
            createdSupportedTagValues?: components["schemas"]["SupportedTagValue"][];
            lastModifiedSupportedTagValues?: components["schemas"]["SupportedTagValue"][];
            createdEntities?: components["schemas"]["Entity"][];
            lastModifiedEntities?: components["schemas"]["Entity"][];
            createdLists?: components["schemas"]["List"][];
            lastModifiedLists?: components["schemas"]["List"][];
        };
        Account: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            /**
             * @default REGISTERED
             * @enum {string}
             */
            type: "REGISTERED" | "CUSTOMER" | "SELLER";
            email?: string | null;
            seller?: components["schemas"]["Seller"] | null;
            customer?: components["schemas"]["Customer"] | null;
            profile?: components["schemas"]["Profile"] | null;
            user?: components["schemas"]["User"];
            userId?: string;
            lists?: components["schemas"]["List"][];
            listings?: components["schemas"]["Listing"][];
            contents?: components["schemas"]["Content"][];
            payouts?: components["schemas"]["Payout"][];
            transactions?: components["schemas"]["Transaction"][];
            carts?: components["schemas"]["Cart"][];
        };
        Customer: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            paymentAccountId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /** @enum {string|null} */
            paymentAccountStatus?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED" | "IN_REVIEW" | null;
            /** @default false */
            hasPaymentMethod: boolean | null;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            orders?: components["schemas"]["Order"][];
        };
        Cart: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            account?: components["schemas"]["Account"];
            accountId?: string;
            orders?: components["schemas"]["Order"][];
        };
        Seller: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            paymentAccountId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            /** @enum {string|null} */
            paymentAccountStatus?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED" | "IN_REVIEW" | null;
            /** @default false */
            isPaymentAccountVerified: boolean | null;
            /** @default false */
            hasPaymentMethod: boolean | null;
            /** @default false */
            agreedToTerms: boolean | null;
            /** @enum {string|null} */
            sellerType?: "INDIVIDUAL" | "BUSINESS" | null;
            taxRate?: number | null;
            firstName?: string | null;
            lastName?: string | null;
            phone?: string | null;
            address?: string | null;
            city?: string | null;
            state?: string | null;
            zipCode?: string | null;
            businessName?: string | null;
            website?: string | null;
            image?: string | null;
            account?: components["schemas"]["Account"];
            accountId?: string;
            orders?: components["schemas"]["Order"][];
        };
        Profile: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            username?: string | null;
            avatar?: string | null;
            banner?: string | null;
            description?: string | null;
            qrCode?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
        };
        Category: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entities?: components["schemas"]["Entity"][];
        };
        Tag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entityTags?: components["schemas"]["EntityTag"][];
            supportedTagValues?: components["schemas"]["SupportedTagValue"][];
        };
        SupportedTagValue: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            banner?: string | null;
            logo?: string | null;
            description?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            tag?: components["schemas"]["Tag"] | null;
            tagId?: string | null;
        };
        List: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            banner?: string | null;
            logo?: string | null;
            description?: string | null;
            /**
             * @default COLLECTION
             * @enum {string|null}
             */
            type: "HOMEPAGE" | "COLLECTION" | "FAVORITE" | "CUSTOM" | null;
            /** @default false */
            isPrivate: boolean | null;
            navigation?: number | string | boolean | Record<string, never> | unknown[] | null;
            index?: number | null;
            referenceCode?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            entityList?: components["schemas"]["EntityList"][];
        };
        Entity: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            name?: string;
            displayName?: string | null;
            description?: string | null;
            /**
             * @default PRODUCT
             * @enum {string}
             */
            type: "PRODUCT" | "SERVICE" | "CONTENT" | "EVENT";
            image?: string | null;
            secondaryImage?: string | null;
            createdBy?: components["schemas"]["Admin"] | null;
            createdById?: string | null;
            lastModifiedBy?: components["schemas"]["Admin"] | null;
            lastModifiedById?: string | null;
            category?: components["schemas"]["Category"] | null;
            categoryId?: string | null;
            content?: components["schemas"]["Content"] | null;
            entityTags?: components["schemas"]["EntityTag"][];
            entityList?: components["schemas"]["EntityList"][];
            listings?: components["schemas"]["Listing"][];
        };
        EntityList: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            quantity?: number | null;
            list?: components["schemas"]["List"];
            listId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        EntityTag: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tagValue?: string;
            isPrimary?: boolean | null;
            index?: number | null;
            tag?: components["schemas"]["Tag"];
            tagId?: string;
            entity?: components["schemas"]["Entity"];
            entityId?: string;
        };
        Content: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default IMAGE
             * @enum {string}
             */
            type: "IMAGE" | "VIDEO" | "GALLERY" | "POST";
            entity?: components["schemas"]["Entity"];
            entityId?: string;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            gallery?: components["schemas"]["Gallery"] | null;
            video?: components["schemas"]["Video"] | null;
            post?: components["schemas"]["Post"] | null;
        };
        Gallery: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            content?: components["schemas"]["Content"];
            contentId?: string;
            images?: components["schemas"]["GalleryImage"][];
        };
        GalleryImage: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            image?: string;
            blurredImage?: string | null;
            caption?: string | null;
            position?: number;
            gallery?: components["schemas"]["Gallery"];
            galleryId?: string;
        };
        Video: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            url?: string | null;
            rawUrl?: string | null;
            /**
             * @default PENDING
             * @enum {string}
             */
            processingStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
            processingError?: string | null;
            duration?: number | null;
            mediaConvertJobId?: string | null;
            content?: components["schemas"]["Content"];
            contentId?: string;
        };
        Post: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            body?: string | null;
            image?: string | null;
            content?: components["schemas"]["Content"];
            contentId?: string;
        };
        Payout: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            status?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED" | "IN_REVIEW";
            total?: number | null;
            last4?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
        };
        Listing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "DELETED" | "INACTIVE";
            /** @default false */
            multiTransactionsEnabled: boolean;
            /** @default false */
            isPrimary: boolean | null;
            /** @default false */
            isOffer: boolean | null;
            image?: string | null;
            imageCaption?: string | null;
            referenceCode?: string | null;
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            entity?: components["schemas"]["Entity"] | null;
            entityId?: string | null;
            orderListings?: components["schemas"]["OrderListing"][];
        };
        Invoice: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DELETED" | "INACTIVE";
            orders?: components["schemas"]["Order"][];
        };
        Order: {
            id?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            deliveredAt?: string | null;
            /** @enum {string} */
            status?: "CREATED" | "DELETED" | "PENDING" | "COMPLETED" | "CANCELED" | "FAILED" | "IN_REVIEW";
            subTotal?: number | null;
            tax?: number | null;
            shipping?: number | null;
            total?: number | null;
            paymentIntentId?: string | null;
            /** @default false */
            inReview: boolean | null;
            resolution?: string | null;
            customerSnapshot?: number | string | boolean | Record<string, never> | unknown[] | null;
            sellerSnapshot?: number | string | boolean | Record<string, never> | unknown[] | null;
            customer?: components["schemas"]["Customer"] | null;
            customerId?: string | null;
            seller?: components["schemas"]["Seller"] | null;
            sellerId?: string | null;
            cart?: components["schemas"]["Cart"] | null;
            cartId?: string | null;
            transactions?: components["schemas"]["Transaction"][];
            invoice?: components["schemas"]["Invoice"] | null;
            invoiceId?: string | null;
            orderListings?: components["schemas"]["OrderListing"][];
        };
        OrderListing: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            quantity?: number | null;
            price?: number | null;
            order?: components["schemas"]["Order"];
            orderId?: string;
            listing?: components["schemas"]["Listing"];
            listingId?: string;
        };
        Transaction: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            amount?: number;
            refundedAmount?: number | null;
            /**
             * @default PAYMENT
             * @enum {string}
             */
            transactionType: "PAYMENT" | "REFUND" | "PAYOUT";
            description?: string | null;
            /**
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "CAD";
            paymentId?: string | null;
            /**
             * @default STRIPE
             * @enum {string}
             */
            paymentAccountType: "STRIPE";
            account?: components["schemas"]["Account"] | null;
            accountId?: string | null;
            order?: components["schemas"]["Order"] | null;
            orderId?: string | null;
            payout?: components["schemas"]["Payout"] | null;
            payoutId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
