import { execSync } from 'child_process'
import * as fs from 'fs'
import * as path from 'path'

const PACKAGE_ROOT = path.resolve(__dirname, '..')
const GENERATED_DIR = path.join(PACKAGE_ROOT, 'generated')
const SRC_DIR = path.join(PACKAGE_ROOT, 'src')
const OPENAPI_PATH = path.join(GENERATED_DIR, 'openapi.json')
const SCHEMAS_OUTPUT = path.join(SRC_DIR, 'oneoff-api-schemas.ts')
const DTO_OUTPUT = path.join(SRC_DIR, 'dto.ts')

// Step 1: Generate OpenAPI wrapper from JSON Schema
console.log('Step 1: Wrapping JSON Schema as OpenAPI document...')
execSync(`npx ts-node ${path.join(__dirname, 'wrap-openapi.ts')}`, {
  stdio: 'inherit',
  cwd: PACKAGE_ROOT,
})

// Step 2: Run openapi-typescript
console.log('Step 2: Generating TypeScript types from OpenAPI...')
execSync(`npx openapi-typescript ${OPENAPI_PATH} -o ${SCHEMAS_OUTPUT}`, {
  stdio: 'inherit',
  cwd: PACKAGE_ROOT,
})

// Step 3: Generate DTO aliases
console.log('Step 3: Generating DTO type aliases...')
const openApiDoc = JSON.parse(fs.readFileSync(OPENAPI_PATH, 'utf-8'))
const schemaNames = Object.keys(openApiDoc.components.schemas)

const dtoLines = [
  '// Auto-generated DTO type aliases.',
  '// Do not edit this file directly -- run `npm run generate` instead.',
  "import type { components } from './oneoff-api-schemas'",
  '',
  ...schemaNames.map(
    (name) => `export type ${name}Dto = components['schemas']['${name}']`
  ),
  '',
]

fs.writeFileSync(DTO_OUTPUT, dtoLines.join('\n'))
console.log(`Generated ${schemaNames.length} DTO aliases in ${DTO_OUTPUT}`)
console.log('Done!')
